package ee.ut.cs.orienteering.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.serialization.Serializable

/**
 * Room entity representing a quest (or lobby) in the application.
 *
 * Each quest contains:
 * - [id] — the autogenerated primary key
 * - [title] — the human‑readable name of the quest
 * - [code] — the unique join code used to enter the lobby
 *
 * This entity is stored in the `quests_table` table and is also annotated
 * with `@Serializable` so it can be included in JSON exports/imports.
 */
@Entity(tableName = "quests_table")
@Serializable
data class Quest (
    @PrimaryKey(autoGenerate = true)
    val id: Int,
    val title: String,
    val code: String
)