package ee.ut.cs.orienteering.data

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import kotlinx.serialization.Serializable

/**
 * Room entity representing a single question belonging to a specific quest.
 *
 * Each question contains:
 * - [id] — the autogenerated primary key
 * - [questId] — foreign key referencing the parent [Quest]
 * - [questionText] — the text shown to the player
 * - [answer] — the expected answer (may be empty for open‑ended questions)
 * - [location] — optional location metadata (e.g., "lat,lon")
 *
 * The entity is stored in the `questions_table` table and is linked to its
 * parent quest via a foreign key with `CASCADE` delete behavior, ensuring that
 * all related questions are removed when a quest is deleted.
 *
 * It is also annotated with `@Serializable` so it can be included in JSON
 * import/export operations.
 */
@Entity(
    tableName = "questions_table",
    foreignKeys = [
        ForeignKey(
            entity = Quest::class,
            parentColumns = ["id"],
            childColumns = ["questId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index(value = ["questId"])]
)
@Serializable
data class Question(
    @PrimaryKey(autoGenerate = true)
    val id: Int,
    val questId: Int,
    val questionText: String,
    val answer: String,
    val location: String
)